{
  "uid" : "134cc2b5fef15836",
  "name" : "test_add_negative",
  "fullName" : "test_calc#test_add_negative",
  "historyId" : "4f6bda658973701365da65bb87a7b7c9",
  "time" : {
    "start" : 1623396179670,
    "stop" : 1623396179670,
    "duration" : 0
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: assert 104 == -96\n +  where 104 = add_numbers(4, -100)",
  "statusTrace" : "def test_add_negative():\n>       assert add_numbers(4, -100) == -96\nE       assert 104 == -96\nE        +  where 104 = add_numbers(4, -100)\n\ntest_calc.py:12: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "test_calc"
  }, {
    "name" : "host",
    "value" : "fv-az83-691"
  }, {
    "name" : "thread",
    "value" : "2812-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_calc"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 3,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 3
      },
      "items" : [ {
        "uid" : "193773ee3f0f22d",
        "reportUrl" : "https://plresearch999.github.io/selenium-py-peldatar/12//#testresult/193773ee3f0f22d",
        "status" : "failed",
        "statusDetails" : "AssertionError: assert 104 == -96\n +  where 104 = add_numbers(4, -100)",
        "time" : {
          "start" : 1623396161255,
          "stop" : 1623396161255,
          "duration" : 0
        }
      }, {
        "uid" : "b58ff5cf21456391",
        "reportUrl" : "https://plresearch999.github.io/selenium-py-peldatar/11//#testresult/b58ff5cf21456391",
        "status" : "failed",
        "statusDetails" : "AssertionError: assert 104 == -96\n +  where 104 = add_numbers(4, -100)",
        "time" : {
          "start" : 1623395480440,
          "stop" : 1623395480440,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "134cc2b5fef15836.json",
  "parameterValues" : [ ]
}